### ISSUE TITLE
Weird its-it dependency

### ISSUE THREAD

**Issue by tovodeverett** [SchemaPlus/schema_plus_enums#4]
When I attempt to run `rake db:schema:dump`, I get:

```
NameError: undefined local variable or method `its' for #<Modware::Stack::Middleware:0x0055df966c6620>
/home/toby/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/schema_plus_enums-0.1.3/lib/schema_plus/enums/middleware.rb:10:in `after
```

If I explicitly add `its-it` to my `Gemfile`, it runs fine.  Which is weird, because `schema_plus_enums` has an explicit dependency on `its-it` (I can see it in `Gemfile.lock`).  The only think I can think of is that perhaps there's a load-order dependency and perhaps it's related to the fact that `modware` no longer has a dependency on `its-it`.

**Comment by ronen** [comment]
my bad.  latest release included the dependency but didn't require the file.  just release v0.1.4 with that fixed.

**Comment by tovodeverett** [comment]
That fixed it :+1: - glad it was easy!
